schemaVersion: 2.1.0
metadata:
  name: hello-world-quarkus
attributes:
  controller.devfile.io/storage-type: ephemeral
commands:
  - exec:
      commandLine: mvn -DskipTests clean install
      component: tools
      group:
        kind: build
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 1-build
  - exec:
      commandLine: 'mvn spring-boot:run'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 2-run
