schemaVersion: 2.2.0
metadata:
  name: hello-world-quarkus
attributes:
  controller.devfile.io/storage-type: ephemeral
projects:
  - git:
      remotes:
        origin: 'https://github.com/liuxiaoyu-git/hello-world-quarkus.git'
    name: hello-world-quarkus
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 1Gi
      memoryRequest: 256Mi
  - name: projects
    volume: {ephemeral: true}
commands:
  - exec:
      commandLine: ./mvnw compile quarkus:dev
      component: tools
      group:
        kind: build
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 1-dev-mode
  - exec:
      commandLine: './mvnw package'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 2-run
