schemaVersion: 2.1.0
metadata:
  name: hello-world-quarkus
  namespace: opentlc-mgr-devspaces
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
  metadata-name-field: generateName
  metadata-name-original-value: hello-world-quarkus
projects:
  - git:
      remotes:
        origin: 'https://github.com/liuxiaoyu-git/hello-world-quarkus.git'
    name: hello-world-quarkus
components:
  - container:
      args:
        - '-f'
        - /dev/null
      command:
        - tail
      image: registry.access.redhat.com/ubi8/openjdk-11
      sourceMapping: /projects
    name: tools
commands:
  - id: runtest
    exec:
      commandLine: mvn package
      component: tools
      group:
        isDefault: true
        kind: build
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
