schemaVersion: 2.1.0
metadata:
  name: hello-world-quarkus
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      ## 可生成 native 程序
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      ## 不可生成 native 程序
      ## image: registry.redhat.io/devspaces/udi-rhel8:3.2
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 4Gi
      memoryRequest: 256Mi
  - name: projects
    volume: {ephemeral: true}
commands:
  - exec:
      commandLine: './mvnw quarkus:dev'
      component: tools
      group:
        kind: build
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 1-build-dev
  - exec:
      commandLine: './mvnw test'
      component: tools
      group:
        kind: test
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 2-test
  - exec:
      commandLine: './mvnw package'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 3-package
  - exec:
      commandLine: 'java -jar target/quarkus-app/quarkus-run.jar'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 4-run-jar
  - exec:
      commandLine: './mvnw install -Dnative -DskipTests -Dquarkus.native.native-image-xmx=4g'
      component: tools
      group:
        kind: build
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 5-native
  - exec:
      commandLine: './target/getting-started-1.0.0-SNAPSHOT-runner'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 6-run-native
  - id: 7-buildimage
    exec:
      label: "Build Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "podman build -f src/main/docker/Dockerfile.jvm -t image-registry.openshift-image-registry.svc:5000/openshift/hello-world-quarkus ."
      group:
        kind: build
  - id: 8-loginlocalregistry
    exec:
      label: "Login to local OpenShift registry"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "podman login --tls-verify=false -u kubeadmin -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000"
      group:
        kind: run
  - id: 9-pushimage
    exec:
      label: "Push Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "podman push --tls-verify=false image-registry.openshift-image-registry.svc:5000/openshift/hello-world-quarkus"
      group:
        kind: build
