schemaVersion: 2.1.0
metadata:
  name: hello-world-quarkus
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 3Gi
      memoryRequest: 256Mi
  - name: projects
    volume: {ephemeral: true}
commands:
  - exec:
      commandLine: './mvnw quarkus:dev'
      component: tools
      group:
        kind: build
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 1-build-dev
  - exec:
      commandLine: './mvnw test'
      component: tools
      group:
        kind: test
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 2-test
  - exec:
      commandLine: './mvnw package'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 3-package
  - exec:
      commandLine: 'java -jar target/quarkus-app/quarkus-run.jar'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 4-run-jar
  - exec:
      commandLine: './mvnw install -Dnative -Dquarkus.native.native-image-xmx=3g'
      component: tools
      group:
        kind: build
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 5-native
  - exec:
      commandLine: './target/getting-started-1.0.0-SNAPSHOT-runner'
      component: tools
      group:
        kind: run
      workingDir: '${PROJECTS_ROOT}/hello-world-quarkus'
    id: 6-run-native
